// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace Switch {
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace Switch

namespace Switch {

namespace protobuf_message_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_message_2eproto

// ===================================================================

class Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Switch.Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Message* other);

  // implements Message ----------------------------------------------

  inline Message* New() const PROTOBUF_FINAL { return New(NULL); }

  Message* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 effects = 6;
  int effects_size() const;
  void clear_effects();
  static const int kEffectsFieldNumber = 6;
  ::google::protobuf::int64 effects(int index) const;
  void set_effects(int index, ::google::protobuf::int64 value);
  void add_effects(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      effects() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_effects();

  // required int64 timestamp = 1;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // required int32 streamType = 2;
  bool has_streamtype() const;
  void clear_streamtype();
  static const int kStreamTypeFieldNumber = 2;
  ::google::protobuf::int32 streamtype() const;
  void set_streamtype(::google::protobuf::int32 value);

  // required int32 operate = 3;
  bool has_operate() const;
  void clear_operate();
  static const int kOperateFieldNumber = 3;
  ::google::protobuf::int32 operate() const;
  void set_operate(::google::protobuf::int32 value);

  // required int64 id = 4;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 4;
  ::google::protobuf::int64 id() const;
  void set_id(::google::protobuf::int64 value);

  // required int32 resourceType = 5;
  bool has_resourcetype() const;
  void clear_resourcetype();
  static const int kResourceTypeFieldNumber = 5;
  ::google::protobuf::int32 resourcetype() const;
  void set_resourcetype(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Switch.Message)
 private:
  void set_has_timestamp();
  void clear_has_timestamp();
  void set_has_streamtype();
  void clear_has_streamtype();
  void set_has_operate();
  void clear_has_operate();
  void set_has_id();
  void clear_has_id();
  void set_has_resourcetype();
  void clear_has_resourcetype();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > effects_;
  ::google::protobuf::int64 timestamp_;
  ::google::protobuf::int32 streamtype_;
  ::google::protobuf::int32 operate_;
  ::google::protobuf::int64 id_;
  ::google::protobuf::int32 resourcetype_;
  friend struct protobuf_message_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Message

// required int64 timestamp = 1;
inline bool Message::has_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Message::set_has_timestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Message::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Message::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::int64 Message::timestamp() const {
  // @@protoc_insertion_point(field_get:Switch.Message.timestamp)
  return timestamp_;
}
inline void Message::set_timestamp(::google::protobuf::int64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:Switch.Message.timestamp)
}

// required int32 streamType = 2;
inline bool Message::has_streamtype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Message::set_has_streamtype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Message::clear_has_streamtype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Message::clear_streamtype() {
  streamtype_ = 0;
  clear_has_streamtype();
}
inline ::google::protobuf::int32 Message::streamtype() const {
  // @@protoc_insertion_point(field_get:Switch.Message.streamType)
  return streamtype_;
}
inline void Message::set_streamtype(::google::protobuf::int32 value) {
  set_has_streamtype();
  streamtype_ = value;
  // @@protoc_insertion_point(field_set:Switch.Message.streamType)
}

// required int32 operate = 3;
inline bool Message::has_operate() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Message::set_has_operate() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Message::clear_has_operate() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Message::clear_operate() {
  operate_ = 0;
  clear_has_operate();
}
inline ::google::protobuf::int32 Message::operate() const {
  // @@protoc_insertion_point(field_get:Switch.Message.operate)
  return operate_;
}
inline void Message::set_operate(::google::protobuf::int32 value) {
  set_has_operate();
  operate_ = value;
  // @@protoc_insertion_point(field_set:Switch.Message.operate)
}

// required int64 id = 4;
inline bool Message::has_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Message::set_has_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Message::clear_has_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Message::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 Message::id() const {
  // @@protoc_insertion_point(field_get:Switch.Message.id)
  return id_;
}
inline void Message::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:Switch.Message.id)
}

// required int32 resourceType = 5;
inline bool Message::has_resourcetype() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Message::set_has_resourcetype() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Message::clear_has_resourcetype() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Message::clear_resourcetype() {
  resourcetype_ = 0;
  clear_has_resourcetype();
}
inline ::google::protobuf::int32 Message::resourcetype() const {
  // @@protoc_insertion_point(field_get:Switch.Message.resourceType)
  return resourcetype_;
}
inline void Message::set_resourcetype(::google::protobuf::int32 value) {
  set_has_resourcetype();
  resourcetype_ = value;
  // @@protoc_insertion_point(field_set:Switch.Message.resourceType)
}

// repeated int64 effects = 6;
inline int Message::effects_size() const {
  return effects_.size();
}
inline void Message::clear_effects() {
  effects_.Clear();
}
inline ::google::protobuf::int64 Message::effects(int index) const {
  // @@protoc_insertion_point(field_get:Switch.Message.effects)
  return effects_.Get(index);
}
inline void Message::set_effects(int index, ::google::protobuf::int64 value) {
  effects_.Set(index, value);
  // @@protoc_insertion_point(field_set:Switch.Message.effects)
}
inline void Message::add_effects(::google::protobuf::int64 value) {
  effects_.Add(value);
  // @@protoc_insertion_point(field_add:Switch.Message.effects)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
Message::effects() const {
  // @@protoc_insertion_point(field_list:Switch.Message.effects)
  return effects_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
Message::mutable_effects() {
  // @@protoc_insertion_point(field_mutable_list:Switch.Message.effects)
  return &effects_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace Switch

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
